#! /usr/bin/env python
# -*- encoding: utf-8 -*-
# vim:fenc=utf-8:

import sys, slimmer

files = sys.argv
files.pop(0)
text = []

for file in files:
    text.append(open(file).read())

print slimmer.css_slimmer(' '.join(text))
